// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZgF8cu1QmsTvXsP-aDWwOvpOKuIF4Zc',
    appId: '1:760270252822:web:3a1eef39d3b7da5322fe37',
    messagingSenderId: '760270252822',
    projectId: 'nov2025-4289c',
    authDomain: 'nov2025-4289c.firebaseapp.com',
    databaseURL: 'https://nov2025-4289c-default-rtdb.firebaseio.com',
    storageBucket: 'nov2025-4289c.firebasestorage.app',
    measurementId: 'G-7GGQ1DMSFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQpvHMjYmuf1Z8cbyOx7iFSm1P_zrwa8',
    appId: '1:760270252822:android:67b2a3aa167ec25522fe37',
    messagingSenderId: '760270252822',
    projectId: 'nov2025-4289c',
    databaseURL: 'https://nov2025-4289c-default-rtdb.firebaseio.com',
    storageBucket: 'nov2025-4289c.firebasestorage.app',
  );

}